-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.github_activity
(
    id serial NOT NULL,
    event_id VARCHAR(40) UNIQUE NOT NULL,
    event_type text NOT NULL,
	repo_owner text NOT NULL,
    repo_name text NOT NULL,
    repo_url text,
	is_private BOOLEAN DEFAULT False,
    action text,
    commit_count integer,
    created_at timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.leetcode_activity
(
    id serial NOT NULL,
    event_id text UNIQUE NOT NULL,
    event_type text NOT NULL CHECK (event_type IN ('Submission','Solution','Contest','Discussion')),
    problem_name text,
    problem_url text,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    status text CHECK (status IN ('Accepted','Wrong Answer','Time Limit Exceeded')),
    difficulty text CHECK (difficulty IN ('Easy','Medium','Hard')),
    runtime text,
    memory text,
    language text,
    solution_url text,
    contest_name text,
    ranking integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.strava_activity
(
    id serial NOT NULL,
    activity_id text UNIQUE NOT NULL,
    activity_type text NOT NULL CHECK (activity_type IN ('Run','Ride','Swim','Hike')),
    name text NOT NULL,
    distance_kms double precision,
    duration_sec integer,
    start_time timestamp without time zone NOT NULL,
    calories_burned double precision,
    average_pace text,
    elevation_gain double precision,
    map_url text,
    PRIMARY KEY (id)
);
END;